"""
UI Dynamic Widget Schemas
-------------------------
Standardized JSON blueprints generated by the Widget Generator Agent.
The Next.js frontend receives these JSON payloads via SSE and mounts the
corresponding interactive React/Recharts components dynamically.
"""

from enum import Enum
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field


class WidgetType(str, Enum):
    METRIC_CARD = "metric_card"
    CHART = "chart"
    TABLE = "table"
    RISK_ITEM = "risk_item"


class MetricCardItem(BaseModel):
    label: str = Field(..., description="Name of metric (e.g., 'Market Cap', 'P/E Ratio')")
    value: Union[str, float, int] = Field(..., description="Current value (e.g., '$3.45T', '31.2')")
    change_percentage: Optional[float] = Field(None, description="Percentage change (+/-)")
    change_direction: Optional[str] = Field("neutral", description="'positive', 'negative', or 'neutral'")
    subtext: Optional[str] = Field(None, description="Contextual note (e.g., 'TTM', '52-week High')")


class MetricCardWidget(BaseModel):
    widget_type: WidgetType = Field(default=WidgetType.METRIC_CARD)
    id: str = Field(..., description="Unique widget identifier")
    title: str = Field(..., description="Section or group title")
    metrics: List[MetricCardItem] = Field(..., description="List of metric items in this card group")


class ChartSeries(BaseModel):
    key: str = Field(..., description="Key corresponding to field in data objects")
    name: str = Field(..., description="Human-readable label for legend")
    color: Optional[str] = Field("#3b82f6", description="Hex color code for line/bar")


class ChartWidget(BaseModel):
    widget_type: WidgetType = Field(default=WidgetType.CHART)
    id: str = Field(..., description="Unique widget identifier")
    title: str = Field(..., description="Title of the chart")
    description: Optional[str] = Field(None, description="Exploratory explanation of the visual")
    chart_kind: str = Field("line", description="'line', 'bar', or 'area'")
    x_axis_key: str = Field(..., description="Field name for horizontal axis (e.g., 'period', 'quarter')")
    series: List[ChartSeries] = Field(..., description="Metrics to plot")
    data: List[Dict[str, Any]] = Field(..., description="Array of data points")


class TableWidget(BaseModel):
    widget_type: WidgetType = Field(default=WidgetType.TABLE)
    id: str = Field(..., description="Unique widget identifier")
    title: str = Field(..., description="Table title")
    description: Optional[str] = Field(None, description="Context or explanation")
    headers: List[str] = Field(..., description="Column display names")
    rows: List[List[Union[str, float, int]]] = Field(..., description="2D matrix of row cells")


class RiskItemWidget(BaseModel):
    widget_type: WidgetType = Field(default=WidgetType.RISK_ITEM)
    id: str = Field(..., description="Unique widget identifier")
    category: str = Field(..., description="Risk category (e.g., 'Regulatory', 'Supply Chain', 'Competition')")
    severity: str = Field("medium", description="'high', 'medium', or 'low'")
    headline: str = Field(..., description="Summary headline of the risk")
    filing_reference: str = Field(..., description="Source citation (e.g., 'SEC 10-K FY2023, Item 1A')")
    summary: str = Field(..., description="Concise analysis of this risk factor")
